### ISSUE TITLE
Include examples of streaming API usage

### ISSUE THREAD

**Issue by nii236** [ChimeraCoder/anaconda#102]
The README doesn't seem to contain any examples for streaming API. The functionality is definitely there, as can be seen in the source and comments.

**Comment by ihrimech** [comment]
Any updates on this functionality ?

**Comment by nii236** [comment]
@ihrimech it looks like the streaming API is implemented but was not documented. As you can see in #116 there is an open pull request for this.

**Comment by ihrimech** [comment]
@nii236 Thanks for the PR. Hope it gets merged and/or updated also with the new one

**Comment by nii236** [comment]
No problem! It wasn't my PR though. Anyway at least some usage information is there, the exported funcs still aren't commented...

**Comment by ChimeraCoder** [comment]
Fixed by #241. Thanks!
