### ISSUE TITLE
Reply to tweet

### ISSUE THREAD

**Issue by emersion** [ChimeraCoder/anaconda#114]
Add a way to send `in_reply_to_status_id` with a tweet when posting.

See https://dev.twitter.com/rest/reference/post/statuses/update

**Comment by lofdev** [comment]
Hey @emersion, you can do this using the current version of the code.  Something like this:

```
v := url.Values{}
v.Set("in_reply_to_status_id", inResponseToID)  //  this is a string value
tweet, err := api.PostTweet("Your tweet text", v)
```

Hope that is helpful.

**Comment by emersion** [comment]
Thanks!
