### ISSUE TITLE
Unexpected property names for Tweet Entities

### ISSUE THREAD

**Issue by logashoff** [ChimeraCoder/anaconda#115]
The returned JSON contains properties such as `Display_url` instead of `display_url` and `Expanded_url` instead of `expanded_url`.

Is there a reason for this? I see some fields do get renamed such as `VideoInfo` to `video_info` on [line 47](https://github.com/ChimeraCoder/anaconda/blob/master/twitter_entities.go#L47), but most don't.

**Comment by muesli** [comment]
#183 fixes this.
