### ISSUE TITLE
Dependency on net/url?

### ISSUE THREAD

**Issue by bobvanluijt** [ChimeraCoder/anaconda#119]
I had to add:
```go
import (
	"net/url"
	"github.com/ChimeraCoder/anaconda"
)
```

Is that correct? If so, maybe nice to mention in the readme.md.

Great lib btw :-)

**Comment by neganp** [comment]
`net/url` is from the Go standard library, so it's not exactly a dependency. You're right that it could be mentioned in the README.

**Comment by ChimeraCoder** [comment]
As Nathaniel mentioned, `net/url` is in the stdlib. Technically, you only need to add it as an import when you're passing `url.Values`, though that is a pretty common use case.


In any case, most Go programmers use `goimports` to keep their imports up-to-date, so I'm not sure it needs to be demonstrated in the README.
