### ISSUE TITLE
[Broken dependecy] azr/backoff updated and broke anaconda

### ISSUE THREAD

**Issue by apognu** [ChimeraCoder/anaconda#120]
Hello,

[azr/backoff](https://github.com/azr/backoff/) commited a change 3 hours ago changing ```backoff.BackOffer``` to ```backoff.Interface```.

Is a quick fix to be expected or should I use a vendored version of the library?

Regards,

**Comment by ChimeraCoder** [comment]
Thanks for noticing this so quickly. I'll fix this.

**Comment by apognu** [comment]
That was luck, you can thank my continuous integration system. ;)
