### ISSUE TITLE
RetweetedStatus contains string like "0xc2084ed700" instead of Tweet object

### ISSUE THREAD

**Issue by MsPseudolus** [ChimeraCoder/anaconda#122]
Hi! Getting great use out of this excellent lib. Thank you!

I need to make use of items in the RetweetedStatus (`retweeted_status`) object, but in all cases where there is a retweet, it looks like this `RetweetedStatus:0xc2084ed700` instead of the full Twitter object which I expect to be there. (When it is not a retweet, it is `RetweetedStatus:<nil>` which is expected.)

Didn't find anyone else reporting this issue, but I can't see a way in which my own code would be causing it. Any ideas?

Thanks!

**Comment by MsPseudolus** [comment]
Update/Solution:

It looks like using a recursive Tweet struct for RetweetedStatus won't work, as the RetweetedStatus object from Twitter contains slightly different stuffs from a standard Tweet object. I created a new struct for the RetweetedStatus object and now it works.

I hope to have time to create a pull request for you next weekend (maybe earlier if lucky).

Thanks!

**Comment by muesli** [comment]
@ChimeraCoder: I think this can be closed as `RetweetedStatus` is a regular `anaconda.Tweet` by now.
