### ISSUE TITLE
There was an error parsing the JSON document. The document may not be well-formed. unexpected non-whitespace character after JSON data at line 2 column 1 

### ISSUE THREAD

**Issue by NikonMcFly** [ChimeraCoder/anaconda#135]
When I use the demo code I get this error in the browser. But if I was to grab a single tweet everything works fine. Does anybody have a work around or is this a bug?

searchResult, _ := api.GetSearch("golang", nil)
for _ , tweet := range searchResult.Statuses {
    w.Header().Set("Content-Type", "Application/json;charset=UTF-8")
    w.WriteHeader(http.StatusOK)
    json.NewEncoder(w).Encode(tweet)
}

**Comment by muesli** [comment]
This code would write an HTTP header and a single JSON document for every single tweet. The second time you send the header it would be part of your response body and hence breaking the JSON encoding. That being said, this has nothing to do with anaconda or its API.
