### ISSUE TITLE
Issue with go get on Windows

### ISSUE THREAD

**Issue by amit-lulla** [ChimeraCoder/anaconda#145]
When downloading this repo as dependency on windows, it gives an error:
"dirty working tree"

The below file name/extension causes the issue:
json/statuses/show.json?id=404409873170841600 as windows does not support this as an extension

Kindly fix it

Thanks

**Comment by amit-lulla** [comment]
error: unable to create file json/statuses/show.json?id=404409873170841600 (Invalid argument)
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by Anon-Penguin** [comment]
This is because there is a question mark in the name of that file, which is an invalid character to use on Windows.

**Comment by muesli** [comment]
Fixed in #174

**Comment by muesli** [comment]
This can be closed now, as #174 got merged.

**Comment by ChimeraCoder** [comment]
Thanks!
