### ISSUE TITLE
Client panicking on `delete` message

### ISSUE THREAD

**Issue by mariokostelac** [ChimeraCoder/anaconda#155]
Last night i've noticed that the stream panicked because of bad memory referencing.
The root cause was https://github.com/ChimeraCoder/anaconda/blob/master/streaming.go#L175. It is not clear if twitter can ever send a message without `delete` being set.

**Comment by mariokostelac** [comment]
I've tried several things and it seems that deserialisation code is correct. It seems that twitter sends bogus message. Will add logging and update the issue.

**Comment by muesli** [comment]
I have a feeling #162 would fix that panic.

**Comment by muesli** [comment]
This should be fixed in master now.
