### ISSUE TITLE
decodeResponse() has a memory leak

### ISSUE THREAD

**Issue by carbocation** [ChimeraCoder/anaconda#196]
The function decodeResponse() in twitter.go does not close the response body in all circumstances. Closure of Response.Body is required as per net/http, even when the body is not used. On my long-running server-side app, this leads to infinite memory growth over time.

Please see #195 for a pull request with a proposed fix.

**Comment by muesli** [comment]
@ChimeraCoder: This can be closed as #195 got merged.
