### ISSUE TITLE
Can't get "quote_count" and "reply_count" after adding to Tweet struct

### ISSUE THREAD

**Issue by hivickylai** [ChimeraCoder/anaconda#216]
These fields are available in the Tweet object, see: https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object

I attempted to add them to the Tweet struct in tweet.go, but this does not appear to produce the correct int (I get `0`). Have I missed something?

**Comment by muesli** [comment]
Can you paste your changes (or open a PR) so I can check them out? Thanks!

**Comment by hivickylai** [comment]
#225

**Comment by manuelmhtr** [comment]
Those fields are available only in Premium APIs >:(
https://twittercommunity.com/t/reply-count-quote-count-not-available-in-statuses-lookup-answer/95241

**Comment by hivickylai** [comment]
Oh. :(
