### ISSUE TITLE
Get all members for a given list

### ISSUE THREAD

**Issue by Rizbe** [ChimeraCoder/anaconda#239]
Is there a current way to get all the members of a list given a list ID?
I have a list with about 500 members that I am trying to get their IDs. 

I can use func GetList, which returns User struct but that will only allow me to set a max count of 200. How would I go about setting a cursor to help me get all 500 ID's?

**Comment by Rizbe** [comment]
https://github.com/ChimeraCoder/anaconda/pull/240

**Comment by ChimeraCoder** [comment]
Thanks for implementing this!
