### ISSUE TITLE
wo get  x509: certificate error

### ISSUE THREAD

**Issue by smirkcat** [ChimeraCoder/anaconda#249]
`panic: Get https://api.twitter.com/1.1/search/tweets.json?q=golang&tweet_mode=extended: x509: certificate is valid for *.facebook.com, *.xx.fbcdn.net, *.fbsbx.com, *.xz.fbcdn.net, *.facebook.net, *.xy.fbcdn.net, *.messenger.com, fb.com, *.fbcdn.net, *.fb.com, *.m.facebook.com, messenger.com, facebook.com, not api.twitter.com
`
and again
`panic: Get https://api.twitter.com/1.1/search/tweets.json?q=golang&tweet_mode=extended: net/http: TLS handshake timeout`

In windows , I use shadowsocks with proxifier

How can I solve it?

**Comment by liukeyou** [comment]
me too

**Comment by zhanzekun** [comment]
how did u solve this problem? qaq
