### ISSUE TITLE
Support statuses/update_with_media endpoint

### ISSUE THREAD

**Issue by carbocation** [ChimeraCoder/anaconda#33]
It would be awesome. If I get the time, I'll try to do it myself.

**Comment by muesli** [comment]
This endpoint is deprecated by now, as per https://dev.twitter.com/rest/reference/post/statuses/update_with_media

I haven't personally tested the `UploadMedia` API of anaconda, but the code exists and that's the proper way to go nowadays.

@ChimeraCoder: can be closed as such.
