### ISSUE TITLE
Cannot install on go 1.2

### ISSUE THREAD

**Issue by syzer** [ChimeraCoder/anaconda#64]
```
go get github.com/ChimeraCoder/anaconda
# github.com/dustin/gojson
../src/github.com/dustin/gojson/encode.go:247: undefined: sync.Pool
```

**Comment by ChimeraCoder** [comment]
What is the output of `$ go version`?

**Comment by syzer** [comment]
`go version go1.2.1 linux/amd64`

**Comment by ChimeraCoder** [comment]
Ah, yes, sync.Pool was added in 1.3: https://golang.org/doc/go1.3

If you update to the current version (1.4, as of a few weeks ago), you should be good to go.

**Comment by ChimeraCoder** [comment]
(Closed the issue while commenting by mistake - please confirm that it works and I'll close it again.)

**Comment by syzer** [comment]
thanks for reply

**Comment by syzer** [comment]
BTW how can i get over 100 geo coordinates associated to tweet (example "Michel Jackson") ?

**Comment by ChimeraCoder** [comment]
There's an outstanding pull request for this (#56); I plan on merging it shortly, though if you need it before then you can also apply the patch manually for the time being.

**Comment by syzer** [comment]
```
go get github.com/ChimeraCoder/anaconda
# github.com/dustin/gojson
/opt/go/pkg/tool/linux_amd64/6g: unknown flag -trimpath
```

**Comment by ChimeraCoder** [comment]
It looks like there's an error with your Go installation. (It also looks like your Go installation is in a non-default location; ie, you have `$GOROOT` set manually to `/opt/go`, which may be related to your issue).
