### ISSUE TITLE
direct_messages/destroy not implemented?

### ISSUE THREAD

**Issue by ghost** [ChimeraCoder/anaconda#74]
https://dev.twitter.com/rest/reference/post/direct_messages/destroy

Can you please implement this? I did not find anything related to it in the godoc.

**Comment by alyak** [comment]
WTF DEVS? BEEN 7 DAYS YO. DO U EVN FKN DO SHIT?

**Comment by ChimeraCoder** [comment]
Sure, looks straightforward - I'll see if I can get to this in the next couple of days.

**Comment by norwack** [comment]
Thanks!

**Comment by norwack** [comment]
Any updates on this?

**Comment by markymark** [comment]
@ChimeraCoder, care to merge/add the implementation of `DeleteDirectMessage()` provided by @jrdnull in #126?

It looks fairly straightforward (and @twitter made the management of DMs through the web UI very cumbersome).

**Comment by ChimeraCoder** [comment]
@markymark Sure thing - just merged it as #184.

**Comment by markymark** [comment]
Very cool--thanks @ChimeraCoder!

Btw I had a great experience with anaconda handling Twitter's rate-limiting for me automatically while fetching friends. No bail on timeout for this library--it simply lies in wait. 🐍

It's the sort of polish that is perhaps never added to a home-grown library. 😄👍
