### ISSUE TITLE
Posting images

### ISSUE THREAD

**Issue by nicolas-martin** [ChimeraCoder/anaconda#95]
Hi, 

I'm posting images (without uploading them) but for some reason I can never get the preview to show up. ie: https://twitter.com/martinni39/status/634554677410054144.

I believe this is on twitters part, but I'd just like to make sure.

**Comment by muesli** [comment]
@nicolas-martin: You need to first upload the media and then attach the media IDs to the `Url.Values` as `media_ids` when sending your tweet.

See: https://dev.twitter.com/rest/reference/post/statuses/update & https://dev.twitter.com/rest/media/uploading-media

@ChimeraCoder: This should resolve this ticket.
