### ISSUE TITLE
"Could not authenticate you."

### ISSUE THREAD

**Issue by laicosly** [ChimeraCoder/anaconda#96]
I can authenticate w/ mrjones/oauth and store the user token/secret, but after that when trying to use anaconda for any api requests just results in the error below.  

I've verified that the consumer key/secret, and user token/secret are referenced correctly, but anaconda just does not want to work for me.  Am I doing something obviously wrong here?

```
Get https://api.twitter.com/1.1/statuses/show.json?id=634839419317456896 returned status 401, {"errors":[{"code":32,"message":"Could not authenticate you."}]}
```

``` go
    anaconda.SetConsumerKey(os.Getenv("TWITTER_KEY"))
    anaconda.SetConsumerSecret(os.Getenv("TWITTER_SECRET"))
    api := anaconda.NewTwitterApi(userToken, userTokenSecret)
    res, err := api.GetTweet(634839419317456896, nil)
```

**Comment by laicosly** [comment]
Can confirm that making a rest api request using mrjones/oauth Consumer.Get with the same consumer key/secret + user token/secret works.  Twitter accepts the authentication, and returns data.

**Comment by Francesco149** [comment]
I know I'm months late, but why not just use the buit-in oauth in anaconda?

```go

	authUrl, tmpCred, err := anaconda.AuthorizationURL("oob")
	if err != nil {
		log.Fatal(err) 
	}

	exec.Command("xdg-open", authUrl).Run()
	fmt.Printf(
		"1. Go to %s (should have opened automatically)\n"+
			"2. Authorize the application\n"+
			"3. Enter verification code: ", authUrl,
	)

	var pin string
	fmt.Scanln(&pin)

	cred, _, err := anaconda.GetCredentials(tmpCred, pin)
	if err != nil {
		log.Fatal(err) 
	}

	api = anaconda.NewTwitterApi(cred.Token, cred.Secret)
	api.SetLogger(anaconda.BasicLogger)

	res, err := api.GetTweet(634839419317456896, nil)
	if err != nil { 
		log.Fatal(err) 
	}
```

**Comment by muesli** [comment]
Looks like this wasn't an issue with anaconda then? Closing this issue, but feel free to comment if you still need clarification. Thanks!
