### ISSUE TITLE
go get issue with dustin/gojson

### ISSUE THREAD

**Issue by totopia** [ChimeraCoder/anaconda#99]
go get github.com/ChimeraCoder/anaconda
# github.com/dustin/gojson

../github.com/dustin/gojson/encode.go:247: undefined: sync.Pool

**Comment by ChimeraCoder** [comment]
What is the output of `go version`?

**Comment by muesli** [comment]
@ChimeraCoder: I assume this can be closed by now.

**Comment by ChimeraCoder** [comment]
Yup, that was almost certainly a result of running with Go <=1.4.
